import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

esbuild
  .build({
    banner: {
      js: banner,
    },
    minify: prod ? true : false,
    entryPoints: ["src/index.ts"],
    bundle: true,
    external: [
      "obsidian",
      "electron",
      "@codemirror/language",
      "@codemirror/state",
      "@codemirror/view",
      ...builtinModules,
    ],
    format: "cjs",
    watch: !prod,
    target: "es2020",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
  })
  .catch(() => process.exit(1));
